process_data:
  features:
    - age
    - education
    - capital.gain
    - hours.per.week
    - race
    - sex
    - occupation
  train_size: 15000

train:
  model_type: gradient_boosting
  n_estimators: 100
  max_depth: 5
  learning_rate: 0.1

evaluate:
  artifact_type: classification_report
